# Project Identification
sonar.projectKey=buy-01-dev
sonar.projectName=buy-01-dev
sonar.organization=violet-ogombo

# Code Analysis
sonar.sources=.
sonar.java.binaries=**/target/classes

# Language and Encoding
sonar.sourceEncoding=UTF-8

# Test Reports
sonar.junit.reportPaths=**/target/surefire-reports

# Exclusions (Build artifacts, dependencies, generated code)
sonar.exclusions=\
  **/node_modules/**,\
  **/.git/**,\
  **/target/**,\
  **/dist/**,\
  **/.angular/**