spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/buy01-test
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
