server:
  port: 8082
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/buy01
  kafka:
    bootstrap-servers: kafka:9092
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
